# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean install server
        run: npm ci

      - name: Clean install client
        run: npm ci --prefix frontend

      - name: Build React app
        run: npm run build --prefix frontend

      - name: Run tests if present
        run: npm test --if-present

      - name: Test that that client build worked and will be served up in production
        run: NODE_ENV=production node backend/server.js
